In [4]:
import os
import re
import pandas as pd
import numpy as np
import sipri
import io
import json

# Importing Data

In [20]:

data = sipri.sipri_data(low_year ='1950',high_year ='2023')
df = pd.read_csv(io.StringIO(data))

In [23]:
data

'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don\'t have permission to access this resource.</p>\n<hr>\n<address>Apache/2.4.29 (Ubuntu) Server at armstrade.sipri.org Port 443</address>\n</body></html>\n'

In [1]:
nrdel_dict = {"1" : "Aircraft",
"14" : "Air defence systems",
"2" : "Artillery",
"3" : "Armoured vehicles",
"4" : "Engines",
"5" : "Sensors",
"6" : "Missiles",
"12" : "Naval weapons",
"11" : "Other",
"13" : "Satellites",
"7" : "Ships"}

In [4]:
nrdel_dict.values()

dict_values(['Aircraft', 'Air defence systems', 'Artillery', 'Armoured vehicles', 'Engines', 'Sensors', 'Missiles', 'Naval weapons', 'Other', 'Satellites', 'Ships'])

In [3]:
mystr = """
"AFG" = Afghanistan
"AU"= African Union**
"ALB" = Albania
"ALG" = Algeria
"ANG" = Angola
"ARG" = Argentina
"ARM" = Armenia
"AUS" = Australia
"AST" = Austria
"AZB" = Azerbaijan
"BAS" = Bahamas
"BAH" = Bahrain
"BAN" = Bangladesh
"BAR" = Barbados
"BLR" = Belarus
"BEL" = Belgium
"BLZ" = Belize
"BEN" = Benin
"BHU" = Bhutan
"BOL" = Bolivia
"BOS" = Bosnia-Herzegovina
"BOT" = Botswana
"BRA" = Brazil
"BRU" = Brunei
"BUL" = Bulgaria
"BF "= Burkina Faso
"BDI" = Burundi
"CAP" = Cabo Verde
"CMB" = Cambodia
"CAM" = Cameroon
"CAN" = Canada
"CAR" = Central African Republic
"CHA" = Chad
"CHE" = Chile
"CHI" = China
"COL" = Colombia
"COM" = Comoros
"CON" = Congo
"COS" = Costa Rica
"IVO" = Cote d'Ivoire
"CRO" = Croatia
"CUB" = Cuba
"CYP" = Cyprus
"CZR" = Czechia
"DRC" = DR Congo
"XSD" = Darfur rebels (Sudan)*
"DEN" = Denmark
"DJI" = Djibouti
"DOM" = Dominican Republic
"ECU" = Ecuador
"EGY" = Egypt
"SAL" = El Salvador
"EQU" = Equatorial Guinea
"ERI" = Eritrea
"EST" = Estonia
"ETH" = Ethiopia
"FJI" = Fiji
"FIN" = Finland
"FRA" = France
"GAB" = Gabon
"GAM" = Gambia
"GEO" = Georgia
"FRG" = Germany
"GHA" = Ghana
"GRE" = Greece
"GUA" = Guatemala
"GUI" = Guinea
"GUY" = Guyana
"XPA" = Hamas (Palestine)*
"XLH" = Hezbollah (Lebanon)*
"HON" = Honduras
"XYH" = Houthi rebels (Yemen)*
"HUN" = Hungary
"ICE" = Iceland
"IND" = India
"INS" = Indonesia
"IRA" = Iran
"IRQ" = Iraq
"IRE" = Ireland
"ISR" = Israel
"ITA" = Italy
"JAM" = Jamaica
"JAP" = Japan
"JOR" = Jordan
"KAZ" = Kazakhstan
"KEN" = Kenya
"KIR" = Kiribati
"KSV" = Kosovo
"KUW" = Kuwait
"KYR" = Kyrgyzstan
"XUL" = LRA (Uganda)*
"XSL" = LTTE (Sri Lanka)*
"LAO" = Laos
"LAT" = Latvia
"LEB" = Lebanon
"LES" = Lesotho
"LIB" = Liberia
"LYA" = Libya
"LYW" = Libya GNC
"LYE" = Libya HoR
"LIT" = Lithuania
"LUX" = Luxembourg
"MAD" = Madagascar
"MWI" = Malawi
"MAL" = Malaysia
"MLV" = Maldives
"MLI" = Mali
"MTA" = Malta
"MAR" = Marshall Islands
"MRA" = Mauritania
"MAU" = Mauritius
"MEX" = Mexico
"MIC" = Micronesia
"MON" = Mongolia
"MTG" = Montenegro
"MOR" = Morocco
"MOZ" = Mozambique
"MYA" = Myanmar
"NAT" = NATO**
"XMN" = NLA (Macedonia)*
"XLB" = NTC (Libya)*
"NAM" = Namibia
"NEP" = Nepal
"NET" = Netherlands
"NZ"= New Zealand
"NIC" = Nicaragua
"NIR" = Niger
"NIG" = Nigeria
"KON" = North Korea
"MAC" = North Macedonia
"XAN" = Northern Alliance (Afghanistan)*
"NOR" = Norway
"OSC" = OSCE**
"OMA" = Oman
"XID" = PIJ (Israel/Palestine)*
"XTP" = PKK (Turkey)*
"XPC" = PRC (Israel/Palestine)*
"PAK" = Pakistan
"PAL" = Palau
"PA"= Palestine
"PAN" = Panama
"PAP" = Papua New Guinea
"PAR" = Paraguay
"PER" = Peru
"PHI" = Philippines
"POL" = Poland
"POR" = Portugal
"QAT" = Qatar
"XSR" = RUF (Sierra Leone)*
"RSS" = Regional Security System**
"ROM" = Romania
"RUS" = Russia
"RWA" = Rwanda
"SAM" = Samoa
"SAU" = Saudi Arabia
"SEN" = Senegal
"SER" = Serbia
"SEY" = Seychelles
"SIE" = Sierra Leone
"SIN" = Singapore
"SLK" = Slovakia
"SLO" = Slovenia
"SOL" = Solomon Islands
"SOM" = Somalia
"SA"= South Africa
"KOS" = South Korea
"SSD" = South Sudan
"SPA" = Spain
"SRI" = Sri Lanka
"SUD" = Sudan
"SUR" = Suriname
"SWE" = Sweden
"SWI" = Switzerland
"SYR" = Syria
"XSX" = Syria rebels*
"TAI" = Taiwan
"TAJ" = Tajikistan
"TAN" = Tanzania
"THA" = Thailand
"ET"= Timor-Leste
"TOG" = Togo
"TON" = Tonga
"TRI" = Trinidad and Tobago
"TUN" = Tunisia
"TUR" = Turkey
"TRK" = Turkmenistan
"TUV" = Tuvalu
"UAE" = UAE
"XSI" = UIC (Somalia)*
"UGA" = Uganda
"UKR" = Ukraine
"XUR" = Ukraine Rebels*
"UK" = United Kingdom
"UNO = United Nations**
"USA" = United States
"XMU" = United Wa State (Myanmar)*
"XXU" = Unknown rebel group*
"XXR" = Unknown recipient(s)
"URU" = Uruguay
"UZB" = Uzbekistan
"VAN" = Vanuatu
"VEN" = Venezuela
"VN"= Viet Nam
"SAH" = Western Sahara
"YEM" = Yemen
"ZAM" = Zambia
"ZIM" = Zimbabwe
"SWA" = eSwatini
"""

mystr = mystr.split("\n")
mystr = mystr[1:-1]
countrycode_dict = {re.search(r'[A-Z]+(?=.*=)',term).group(0) : re.search(r"(?<==\s).*$",term).group(0) for term in mystr}

In [ ]:
#store coutnrycode_dict
countries = list(countrycode_dict.values())
with open('country_list.json',"w") as json_file:
    json.dump(countries,json_file)

# Data Cleaning

In [ ]:
df = pd.read_csv()

In [19]:
df['delyears'].compare(df['ldat'])
df.head(1)

KeyError: 'delyears'

In [ ]:
df.columns = ['id','buyer_code','seller_code','order_year','order_year_estimated','number_ordered','number_ordered_estimated','last_delivery','comment1','weapon_designation',
              'weapon_category','weapon_subcategory','coprod','number_delivered','number_delivered_estimated','delivered_year','buyer_name','seller_name','status','tivunit','tivorder','tivdel']
df.head(10)
#df.onum.compare(df.nrdel)

,id,buyer_code,seller_code,order_year,order_year_estimated,number_ordered,number_ordered_estimated,last_delivery,comment1,weapon_designation,...,coprod,number_delivered,number_delivered_estimated,delivered_year,buyer_name,seller_name,status,tivunit,tivorder,tivdel
0,55238,BF,ALB,2011,X,12.0,X,2011,NaN,PM-43 120mm,...,L,12.0,NaN,2011,Burkina Faso,Albania,S,0.020,0.240,0.240
1,3622,ANG,ALG,1980,NaN,4.0,NaN,1980,NaN,N-262 Fregate,...,L,4.0,NaN,1980,Angola,Algeria,S,1.500,6.000,6.000
2,11246,NIG,ALG,1967,NaN,2.0,X,1968,NaN,Il-28,...,L,2.0,X,1968,Nigeria,Algeria,S,2.880,5.760,5.760
3,60840,SAH,ALG,2016,X,3.0,X,2016,AID,BTR-60PB,...,L,3.0,X,2016,Western Sahara,Algeria,S,0.100,0.300,0.300
4,3667,CON,ANG,1979,NaN,1.0,NaN,1979,AID,Noratlas,...,L,1.0,NaN,1979,Congo,Angola,S,2.800,2.800,2.800
5,3684,GBI,ANG,1980,NaN,1.0,NaN,1980,NaN,Do-27,...,L,1.0,NaN,1980,Guinea-Bissau,Angola,S,0.048,0.048,0.048
6,33777,IVO,ANG,2002,NaN,2.0,X,2002,NaN,BMP-2,...,L,2.0,X,2002,Cote d'Ivoire,Angola,S,0.360,0.720,0.720
7,33871,IVO,ANG,2002,NaN,2.0,NaN,2002,NaN,T-55,...,L,2.0,NaN,2002,Cote d'Ivoire,Angola,S,0.500,1.000,1.000
8,31645,BOL,ARG,2006,NaN,37.0,X,2006,AID,M-3/M-5 Half-track,...,L,37.0,X,2006,Bolivia,Argentina,S,0.060,2.220,2.220
9,19781,COL,ARG,1989,NaN,3.0,NaN,1990,AID,IA-58A Pucara,...,L,3.0,NaN,1990,Colombia,Argentina,S,2.000,6.000,6.000

## Saving the Work